version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyecto_frontend_app
    restart: always
    ports:
      - "5000:5000" 
    environment:
      
      - BACKEND_URL=http://proyecto_backend_api:3000
      
    networks:
      - red_innovatech_global

networks:
  red_innovatech_global:
    external: true