version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyecto_frontend_app
    restart: always
    ports:
      - "5000:5000" # Cambiar el primer "5000" si deseas mapearlo a otro puerto en tu máquina local
    environment:
      # Variable crítica para que el Python sepa dónde ir a buscar los datos del backend localmente
      - BACKEND_URL=http://localhost:3000
      # Si tu archivo .env.example del front tiene más variables,agrégalas aquí abajo en el mismo formato
    networks:
      - red_innovatech_global

networks:
  red_innovatech_global:
    external: true